# Generated by Django 2.2.5 on 2019-09-28 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogposts',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
