# Generated by Django 2.2.5 on 2019-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190928_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposts',
            options={'ordering': ['-published_date', '-updated', '-timestamp']},
        ),
    ]
