# Generated by Django 2.2.5 on 2019-09-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190928_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
