# Generated by Django 2.2.5 on 2019-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
